### ISSUE TITLE
Solvers can find different models, and this must not make Matchers behave incorrectly when pretty-printing counter examples

### ISSUE THREAD

**Issue by strikef** [aqjune/mlir-tv#118]
When printing counterexamples, different solvers may return terms of different op structure, causing `smt::Matcher` to malfunction
ex)
> z3 expr: (store ((as const (Array (_ BitVec 32) (_ BitVec 4))) #x1) #x00000088 #xc)
cvc5 term: (store (store (store ((as const (Array (_ BitVec 32) (_ BitVec 4))) #b0001) #b00000000000000000000001111101111 #b1111) #b00000000000000000000001101101000 #b1110) #b00000000000000000000001011111111 #b0111)

**Comment by aqjune** [comment]
We do not support running multiple solvers at once anymore; closing the issue.
