### ISSUE TITLE
Compilation failed with the newest LLVM build (PadTensorOP Removed)

### ISSUE THREAD

**Issue by Hatsunespica** [aqjune/mlir-tv#312]
Looks like they removed this Op in the newest LLVM build. 
PadTensorOp was also removed from the doc
https://mlir.llvm.org/doxygen/structmlir_1_1linalg_1_1PadTensorOpTransformationPattern.html

below is the error message.

/home/spica/GitRepo/mlir-tv/src/analysis.cpp:295:30: error: ‘PadTensorOp’ is not a member of ‘mlir::linalg’; did you mean ‘InitTensorOp’?
  295 | bool analyzeOp(mlir::linalg::PadTensorOp op, AnalysisResult &res) {
      |                              ^~~~~~~~~~~
      |                              InitTensorOp
/home/spica/GitRepo/mlir-tv/src/analysis.cpp:295:61: error: expected primary-expression before ‘&’ token
  295 | bool analyzeOp(mlir::linalg::PadTensorOp op, AnalysisResult &res) {
      |                                                             ^
/home/spica/GitRepo/mlir-tv/src/analysis.cpp:295:62: error: ‘res’ was not declared in this scope
  295 | bool analyzeOp(mlir::linalg::PadTensorOp op, AnalysisResult &res) {
      |                                                              ^~~
/home/spica/GitRepo/mlir-tv/src/analysis.cpp:295:65: error: expression list treated as compound expression in initializer [-fpermissive]
  295 | bool analyzeOp(mlir::linalg::PadTensorOp op, AnalysisResult &res) {
      |                                                                 ^
/home/spica/GitRepo/mlir-tv/src/analysis.cpp:295:6: warning: too many template headers for ‘{anonymous}::analyzeOp’ (should be 0)
  295 | bool analyzeOp(mlir::linalg::PadTensorOp op, AnalysisResult &res) {
      |      ^~~~~~~~~
/home/spica/GitRepo/mlir-tv/src/analysis.cpp:295:66: error: expected ‘;’ before ‘{’ token
  295 | bool analyzeOp(mlir::linalg::PadTensorOp op, AnalysisResult &res) {
      |                                                                  ^~
      |

**Comment by strikef** [comment]
Thank you for reporting this issue!
We've been staying on previous LLVM build ([b5a0f0f](https://github.com/llvm/llvm-project/commit/b5a0f0f397c778cc7db71754c1b9c939f669568e)) for a while, so it won't compile with latest LLVM. There's a patch waiting to be merged, so it will hopefully be fixed soon :)
